[package]
name = "musicbrainz"
description = "MusicBrainz API bindings for Rust"
license = "MIT"
version = "0.1.0"
authors = ["Alexandre Oliveira <rockytvbr@gmail.com>"]

[dependencies]
hyper = "0.9.10"
json = "0.10.2"
